export COLORTERM=truecolor

# >>> oh-my-zsh initialize >>>
export ZSH="$HOME/.oh-my-zsh"
export MANPATH="/usr/local/man:$MANPATH"
export ARCHFLAGS="-arch x86_64"
ZSH_THEME=half-life

zstyle ':omz:update' mode disabled
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(
  git 
  zsh-completions
  zsh-syntax-highlighting
  zsh-autosuggestions
  web-search
  extract 
)
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
source $ZSH/oh-my-zsh.sh
# <<< oh-my-zsh initialize <<<

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/yuanyin/.local/anaconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/yuanyin/.local/anaconda/etc/profile.d/conda.sh" ]; then
        . "/home/yuanyin/.local/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/home/yuanyin/.local/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

[ -s "${HOME}/.config/profile" ] && source ${HOME}/.config/profile

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -s "/home/linuxbrew/.linuxbrew/bin/brew" ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
# [ -s "/home/linuxbrew/.linuxbrew/bin/oh-my-posh" ] && eval "$(oh-my-posh init zsh --config $(brew --prefix oh-my-posh)/themes/gruvbox.omp.json)"
[ -s "/usr/bin/zoxide" ] && eval "$(zoxide init zsh)"

bindkey '^u' backward-kill-line
bindkey '\ef' emacs-forward-word
