if has("gui_running")
  if has("gui_gtk2")
    set guifont=JetBrainsMono\ NFM\ 14
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h12
  elseif has("gui_win32")
    set guifont=JetBrainsMono_NFM:h12
  endif
endif

set guioptions-=m       " remove menu bar
set guioptions-=T       " remove toolbar
set guioptions-=r       " remove right-hand scroll bar
set guioptions-=L       " remove left-hand scroll bar
set visualbell t_vb=
autocmd GUIEnter * set t_vb=

set lines=40
set columns=120
